import "./globals.css";
import { GlobalStyles } from "@mui/material";
import Modal from "./component/modal/Modal";
import Alerts from "./component/alert/Alerts";
import Header from "./component/header/Header";
import ThemeMode from "./component/darklight/ThemeMode";
import MiniDrawer from "./component/sidebar/MiniDrawer";
import { Grid } from "@mui/material";
import Footer from "./component/footer/Footer";
import DrawerMobile from "./component/sidebar/DrawerMobile";
export const metadata = {
  title: "Panel Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no"
        />
      </head>
      <body>
        <GlobalStyles
          styles={{
            body: {
              overflowX: "hidden",
              margin: 0,
              padding: 0,
              width: "100%",
              maxWidth: "100%",
            },
          }}
        />
        <ThemeMode>
          <Alerts />
          <Modal>
            <Grid container spacing={3} padding={1}>
              <Grid size="auto" display={{ xs: "none", md: "unset" }}>
                <MiniDrawer />
              </Grid>
              <Grid container direction={"column"} size="grow">
                <Header />
                <DrawerMobile />
                {children}
                <Footer />
              </Grid>
            </Grid>
          </Modal>
        </ThemeMode>
      </body>
    </html>
  );
}
